---
- hosts: all
  vars:
    sudoers:
      - suporte-gcp
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.200 gcloud-client

    - name: Adiciona o usuario suporte-gcp
      user:
        name: suporte-gcp
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Adicionar usuarios ao grupo wheel
      lineinfile:
        path: /etc/sudoers
        line: "{{ item }}"
      with_items:
        - 'suporte-gcp ALL=(ALL) NOPASSWD: ALL'

    - name: Configura o servidor SSH para permitir conexao por senha
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication no'
        replace: 'PasswordAuthentication yes'

    - name: Reinicia o SSH
      service:
        name: sshd
        daemon_reload: yes
        state: restarted
