version: '3'
services:
  db-server:
    image: "mysql:5.7"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://GRAYLOG_SERVER:12201"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "Abc123"
      MYSQL_DATABASE: php
      MYSQL_USER: php
      MYSQL_PASSWORD: 4linux
    ports:
      - "3306:3306"
    volumes:
      - "/opt/data:/var/lib/mysql"
#       - "/var/log/mysql:/var/log/mysql"
#       - "/570/config/my.cnf:/etc/my.cnf"
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
#     logging:
#       driver: "gcplogs"
#       options:
#         gcp-meta-name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"
  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysqld-exporter
    restart: unless-stopped
    command:
     - "--mysqld.username=php:4linux"
     - "--mysqld.address=db-server:3306"
    ports:
      - "9104:9104"
